services:
  # koda Service
  - type: web
    name: fubs-koda
    plan: free
    env: docker
    dockerfilePath: ./apps/koda/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: koda-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
    healthCheckPath: /health

databases:
  - name: koda-db
    plan: free
