services:
  # Tasks Service
  - type: web
    name: fubs-tasks
    plan: free
    env: docker
    dockerfilePath: ./apps/tasks/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: tasks-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: RABBITMQ_URL
      - key: RABBITMQ_QUEUE
    healthCheckPath: /health

databases:
  - name: tasks-db
    plan: free
