// example subscription object from stripe
export const mockSubscription = {
  id: 'sub_1S42cGCLMvMPoLmVikNe1HCl',
  object: 'subscription',
  application: null,
  application_fee_percent: null,
  automatic_tax: {
    disabled_reason: null,
    enabled: false,
    liability: null,
  },
  billing_cycle_anchor: 1757090158,
  billing_cycle_anchor_config: null,
  billing_mode: {
    type: 'classic',
  },
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: {
    comment: null,
    feedback: null,
    reason: null,
  },
  collection_method: 'charge_automatically',
  created: 1757090158,
  currency: 'usd',
  customer: 'cus_T02gKTp3FX2p2g',
  days_until_due: null,
  default_payment_method: 'pm_1S42cECLMvMPoLmV8vtXwdHe',
  default_source: null,
  default_tax_rates: [],
  description: null,
  discounts: [],
  ended_at: null,
  invoice_settings: {
    account_tax_ids: null,
    issuer: {
      type: 'self',
    },
  },
  items: {
    object: 'list',
    data: [
      {
        id: 'si_T02hgpCgJzIXRi',
        object: 'subscription_item',
        billing_thresholds: null,
        created: 1757090159,
        current_period_end: 1759682158,
        current_period_start: 1757090158,
        discounts: [],
        metadata: {},
        plan: {
          id: 'price_1S42PjCLMvMPoLmVZgiUIfOc',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: '0',
          billing_scheme: 'per_unit',
          created: 1757089383,
          currency: 'usd',
          interval: 'month',
          interval_count: 1,
          livemode: false,
          metadata: {},
          meter: null,
          nickname: null,
          product: 'prod_T02U3JFVaB8HoB',
          tiers_mode: null,
          transform_usage: null,
          trial_period_days: null,
          usage_type: 'licensed',
        },
        price: {
          id: 'price_1S42PjCLMvMPoLmVZgiUIfOc',
          object: 'price',
          active: true,
          billing_scheme: 'per_unit',
          created: 1757089383,
          currency: 'usd',
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: 'prod_T02U3JFVaB8HoB',
          recurring: {
            interval: 'month',
            interval_count: 1,
            meter: null,
            trial_period_days: null,
            usage_type: 'licensed',
          },
          tax_behavior: 'unspecified',
          tiers_mode: null,
          transform_quantity: null,
          type: 'recurring',
          unit_amount: 0,
          unit_amount_decimal: '0',
        },
        quantity: 1,
        subscription: 'sub_1S42cGCLMvMPoLmVikNe1HCl',
        tax_rates: [],
      },
    ],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_1S42cGCLMvMPoLmVikNe1HCl',
  },
  latest_invoice: 'in_1S42cFCLMvMPoLmVidkzzUb1',
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: {
        network: null,
        request_three_d_secure: 'automatic',
      },
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: ['card'],
    save_default_payment_method: 'off',
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'price_1S42PjCLMvMPoLmVZgiUIfOc',
    object: 'plan',
    active: true,
    amount: 0,
    amount_decimal: '0',
    billing_scheme: 'per_unit',
    created: 1757089383,
    currency: 'usd',
    interval: 'month',
    interval_count: 1,
    livemode: false,
    metadata: {},
    meter: null,
    nickname: null,
    product: 'prod_T02U3JFVaB8HoB',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed',
  },
  quantity: 1,
  schedule: null,
  start_date: 1757090158,
  status: 'active',
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: {
    end_behavior: {
      missing_payment_method: 'create_invoice',
    },
  },
  trial_start: null,
};
