// example checkout-session object from stripe

export const stripeCheckoutSessionMock = {
  id: 'cs_test_a1WRakawTby3zfhzQtXmnat67ivgDz2tINdqdqP6y3uCKThkBushRtg6xp',
  object: 'checkout.session',
  adaptive_pricing: {
    enabled: false,
  },
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 0,
  amount_total: 0,
  automatic_tax: {
    enabled: false,
    liability: null,
    provider: null,
    status: null,
  },
  billing_address_collection: null,
  cancel_url: 'https://example.com/cancel',
  client_reference_id: null,
  client_secret: null,
  collected_information: {
    shipping_details: null,
  },
  consent: null,
  consent_collection: null,
  created: 1757090135,
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: 'cus_T02gKTp3FX2p2g',
  customer_creation: null,
  customer_details: {
    address: {
      city: null,
      country: 'BR',
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    email: 'tassio72@gmail.com',
    name: 'Tassio',
    phone: null,
    tax_exempt: 'none',
    tax_ids: [],
  },
  customer_email: null,
  discounts: [],
  expires_at: 1757176535, // we might use this to save expiration date in our db
  invoice: 'in_1S42cFCLMvMPoLmVidkzzUb1',
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {
    ownerId: '3bfd1da0-64b2-4564-be03-85936c4ce8ff',
  },
  mode: 'subscription',
  origin_context: null,
  payment_intent: null,
  payment_link: null,
  payment_method_collection: 'always',
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      request_three_d_secure: 'automatic',
    },
  },
  payment_method_types: ['card'],
  payment_status: 'paid',
  permissions: null,
  phone_number_collection: {
    enabled: false,
  },
  recovered_from: null,
  saved_payment_method_options: {
    allow_redisplay_filters: ['always'],
    payment_method_remove: 'disabled',
    payment_method_save: null,
  },
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_options: [],
  status: 'complete',
  submit_type: null,
  subscription: 'sub_1S42cGCLMvMPoLmVikNe1HCl',
  success_url: 'https://example.com/success',
  total_details: {
    amount_discount: 0,
    amount_shipping: 0,
    amount_tax: 0,
  },
  ui_mode: 'hosted',
  url: null,
  wallet_options: null,
};
