name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # ignore e2e until we have a stable e2e test
      - name: Run Affected Tests
        run: yarn nx affected -t test --base=origin/main --head=HEAD --parallel=10 --verbose --exclude="@fubs/workspaces-e2e"
      - name: Run Affected Builds
        run: yarn nx affected -t build --base=origin/main --head=HEAD --parallel=10 --verbose
      - name: Run Affected Lint
        run: yarn nx affected -t lint --base=origin/main --head=HEAD --parallel=10 --verbose
