name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
        # ignore e2e until we have a stable e2e test
      - run: yarn nx affected -t lint test build --exclude="@fubs/workspaces-e2e"
